// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA59MeLTG_YjN1u5P7uyY7yPtumKyMKdQ4',
    appId: '1:712887098943:web:e139b2a8eeddd47f94e28a',
    messagingSenderId: '712887098943',
    projectId: 'prakflutterfirebase-24a4b',
    authDomain: 'prakflutterfirebase-24a4b.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-24a4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD05mkcAHxr-fgPnh-H3vqH_PuiYX6yIz4',
    appId: '1:712887098943:android:8123a369fb20d83094e28a',
    messagingSenderId: '712887098943',
    projectId: 'prakflutterfirebase-24a4b',
    storageBucket: 'prakflutterfirebase-24a4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBorfhqaux-WyymrObik8SnnO6lTeHsDlA',
    appId: '1:712887098943:ios:cd24564e2fdaaab394e28a',
    messagingSenderId: '712887098943',
    projectId: 'prakflutterfirebase-24a4b',
    storageBucket: 'prakflutterfirebase-24a4b.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBorfhqaux-WyymrObik8SnnO6lTeHsDlA',
    appId: '1:712887098943:ios:cd24564e2fdaaab394e28a',
    messagingSenderId: '712887098943',
    projectId: 'prakflutterfirebase-24a4b',
    storageBucket: 'prakflutterfirebase-24a4b.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA59MeLTG_YjN1u5P7uyY7yPtumKyMKdQ4',
    appId: '1:712887098943:web:d369f8f63383e7c994e28a',
    messagingSenderId: '712887098943',
    projectId: 'prakflutterfirebase-24a4b',
    authDomain: 'prakflutterfirebase-24a4b.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-24a4b.appspot.com',
  );
}
